### ISSUE TITLE
Very nice extension, but could you add an option to disable the highlighting

### ISSUE THREAD

**Issue by vladmashk** [ackinc/keep-twitter-scroll-position#1]

**Comment by ackinc** [comment]
Hi Vlad, just to understand the problem better: is this because the highlighting is too bright when browsing Twitter in dark-mode?

**Comment by vladmashk** [comment]
Yeah, mostly that

**Comment by ackinc** [comment]
Adding a settings pane seems like too much effort right now, so I've changed the extension to use a dark-mode-friendly highlight color when browsing in dark mode. Hope that fixes your problem!

**Comment by vladmashk** [comment]
Yes, it's better now
